name: Debezium Connect Update

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - qa
          - stage
          - prod
permissions:
  id-token: write
  contents: read

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::540464586484:role/cdc-streaming-github-actions-role
          aws-region: "ap-northeast-2"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run Debezium Connect Update
        run: ./debezium ${{ github.event.inputs.environment }}