name: KSQL Update

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - qa
          - stage
          - prod

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build KSQL Updater
        run: go build -o ksql ./cmd/ksql

      - name: Run KSQL Update
        run: ./ksql ${{ github.event.inputs.environment }}